"""add parties and files

Revision ID: 2d0855feea3b
Revises: 331450588688
Create Date: 2026-08-18 23:26:28.024669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0855feea3b'
down_revision: Union[str, Sequence[str], None] = '331450588688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Путь к файлу'),
    sa.Column('file_type', sa.String(length=30), nullable=False, comment='Тип файла'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Исходное имя'),
    sa.Column('size', sa.Integer(), nullable=False, comment='Размер (байт)'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME тип'),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True, comment='Кем загружен'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties_delivery_zone',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parties_address',
    sa.Column('full_address', sa.Text(), nullable=False, comment='Полный адрес'),
    sa.Column('fias_id', sa.String(length=36), nullable=False, comment='FIAS ID'),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True, comment='Широта'),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True, comment='Долгота'),
    sa.Column('postal_code', sa.String(length=10), nullable=False, comment='Индекс'),
    sa.Column('delivery_zone_id', sa.Integer(), nullable=True, comment='Зона доставки'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['parties_delivery_zone.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties_legal_entity',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Краткое наименование'),
    sa.Column('legal_name', sa.String(length=255), nullable=False, comment='Полное наименование'),
    sa.Column('inn', sa.String(length=12), nullable=False, comment='ИНН'),
    sa.Column('kpp', sa.String(length=9), nullable=False, comment='КПП'),
    sa.Column('ogrn', sa.String(length=15), nullable=False, comment='ОГРН'),
    sa.Column('legal_address_id', sa.Integer(), nullable=True, comment='Юридический адрес'),
    sa.Column('actual_address_id', sa.Integer(), nullable=True, comment='Фактический адрес'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Телефон'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email'),
    sa.Column('edo_uuid', sa.String(length=36), nullable=True, comment='Идентификатор ЭДО'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['actual_address_id'], ['parties_address.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['legal_address_id'], ['parties_address.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties_raw_address',
    sa.Column('raw_text', sa.Text(), nullable=False, comment='Сырой адрес'),
    sa.Column('hash', sa.String(length=64), nullable=False, comment='SHA256 от нормализованного'),
    sa.Column('normalized_address_id', sa.Integer(), nullable=False, comment='Нормализованный адрес'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Источник'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['normalized_address_id'], ['parties_address.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('parties_carrier',
    sa.Column('legal_entity_id', sa.Integer(), nullable=False, comment='Юрлицо'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['parties_legal_entity.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_entity_id')
    )
    op.create_table('parties_contract',
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер договора'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Заказчик'),
    sa.Column('executor_id', sa.Integer(), nullable=False, comment='Исполнитель'),
    sa.Column('contract_type', sa.String(length=20), nullable=False, comment='Тип договора'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Дата начала'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Дата окончания'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус'),
    sa.Column('terms', sa.JSON(), nullable=False, comment='Условия'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties_legal_entity.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['parties_legal_entity.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties_depositor',
    sa.Column('legal_entity_id', sa.Integer(), nullable=False, comment='Юрлицо'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Код поклажедателя'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['parties_legal_entity.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_entity_id')
    )
    op.create_table('parties_keeper',
    sa.Column('legal_entity_id', sa.Integer(), nullable=False, comment='Юрлицо'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['parties_legal_entity.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_entity_id')
    )
    op.create_table('accounts_user_depositor',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.Column('depositor_id', sa.Integer(), nullable=False, comment='Поклажедатель'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['depositor_id'], ['parties_depositor.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'depositor_id', name='uq_user_depositor')
    )
    op.create_table('parties_client',
    sa.Column('depositor_id', sa.Integer(), nullable=False, comment='Поклажедатель'),
    sa.Column('external_id', sa.String(length=50), nullable=False, comment='Внешний код'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Наименование'),
    sa.Column('legal_name', sa.String(length=255), nullable=False, comment='Полное наименование'),
    sa.Column('inn', sa.String(length=12), nullable=False, comment='ИНН'),
    sa.Column('kpp', sa.String(length=9), nullable=False, comment='КПП'),
    sa.Column('legal_address_id', sa.Integer(), nullable=True, comment='Юридический адрес'),
    sa.Column('is_edo', sa.Boolean(), nullable=False, comment='Признак ЭДО'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['depositor_id'], ['parties_depositor.id'], ),
    sa.ForeignKeyConstraint(['legal_address_id'], ['parties_address.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depositor_id', 'external_id', name='uq_client_depositor_external')
    )
    op.create_table('parties_tariff_document',
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='Договор'),
    sa.Column('document_type', sa.String(length=20), nullable=False, comment='Тип документа'),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер'),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата подписания'),
    sa.Column('valid_from', sa.Date(), nullable=False, comment='Действует с'),
    sa.Column('valid_until', sa.Date(), nullable=True, comment='Действует до'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Валюта'),
    sa.Column('vat_rate', sa.String(length=10), nullable=False, comment='Ставка НДС'),
    sa.Column('file_id', sa.Integer(), nullable=True, comment='Скан документа'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['contract_id'], ['parties_contract.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties_tariff',
    sa.Column('document_id', sa.Integer(), nullable=False, comment='Тарифный документ'),
    sa.Column('service_group', sa.String(length=20), nullable=False, comment='Группа услуг'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Единица измерения'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Цена'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['parties_tariff_document.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties_trade_point',
    sa.Column('client_id', sa.Integer(), nullable=False, comment='Клиент'),
    sa.Column('address_id', sa.Integer(), nullable=False, comment='Адрес'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['address_id'], ['parties_address.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['parties_client.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'address_id', name='uq_trade_point_client_address')
    )
    op.create_table('accounts_user_trade_point',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.Column('trade_point_id', sa.Integer(), nullable=False, comment='Торговая точка'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['trade_point_id'], ['parties_trade_point.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_point_id', name='uq_user_trade_point')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts_user_trade_point')
    op.drop_table('parties_trade_point')
    op.drop_table('parties_tariff')
    op.drop_table('parties_tariff_document')
    op.drop_table('parties_client')
    op.drop_table('accounts_user_depositor')
    op.drop_table('parties_keeper')
    op.drop_table('parties_depositor')
    op.drop_table('parties_contract')
    op.drop_table('parties_carrier')
    op.drop_table('parties_raw_address')
    op.drop_table('parties_legal_entity')
    op.drop_table('parties_address')
    op.drop_table('parties_delivery_zone')
    op.drop_table('files')
    # ### end Alembic commands ###
