"""initial accounts

Revision ID: 331450588688
Revises: 
Create Date: 2026-08-18 22:44:44.739002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '331450588688'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_user',
    sa.Column('username', sa.String(length=64), nullable=False, comment='Имя пользователя'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хэш пароля'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Телефон'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Суперпользователь'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_username'), 'accounts_user', ['username'], unique=True)
    op.create_table('accounts_audit',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='Действие'),
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment='Тип сущности'),
    sa.Column('entity_id', sa.String(length=36), nullable=True, comment='ID сущности'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Изменения'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IP адрес'),
    sa.Column('user_agent', sa.String(length=500), nullable=False, comment='User Agent'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_role',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Код'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Права'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts_user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.Column('menu_style', sa.String(length=10), nullable=False, comment='Стиль меню'),
    sa.Column('theme', sa.String(length=10), nullable=False, comment='Тема'),
    sa.Column('density', sa.String(length=15), nullable=False, comment='Плотность'),
    sa.Column('font_size', sa.String(length=10), nullable=False, comment='Размер шрифта'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('accounts_user_table_settings',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.Column('table_id', sa.String(length=50), nullable=False, comment='Идентификатор таблицы'),
    sa.Column('columns_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Порядок колонок'),
    sa.Column('hidden_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Скрытые колонки'),
    sa.Column('column_widths', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ширина колонок'),
    sa.Column('page_size', sa.Integer(), nullable=False, comment='Размер страницы'),
    sa.Column('default_ordering', sa.String(length=50), nullable=False, comment='Сортировка'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'table_id', name='uq_user_table_settings')
    )
    op.create_table('accounts_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['accounts_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts_user_roles')
    op.drop_table('accounts_user_table_settings')
    op.drop_table('accounts_user_settings')
    op.drop_table('accounts_role')
    op.drop_table('accounts_audit')
    op.drop_index(op.f('ix_accounts_user_username'), table_name='accounts_user')
    op.drop_table('accounts_user')
    # ### end Alembic commands ###
