"""make delivery_address_id nullable

Revision ID: 398d85319f7a
Revises: 84d402625be3
Create Date: 2026-08-21 16:59:56.651184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398d85319f7a'
down_revision: Union[str, Sequence[str], None] = '84d402625be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parties_client', 'delivery_address_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Адрес доставки')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parties_client', 'delivery_address_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Адрес доставки')
    # ### end Alembic commands ###
