"""extend integration log

Revision ID: 3da6fcf45d11
Revises: c175f41bdbc5
Create Date: 2026-08-21 18:22:49.991475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3da6fcf45d11'
down_revision: Union[str, Sequence[str], None] = 'c175f41bdbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_log', sa.Column('task_id', sa.String(length=36), nullable=False, comment='UUID задачи импорта'))
    op.add_column('integration_log', sa.Column('document_type', sa.String(length=20), nullable=True, comment='Тип: porder, order, all'))
    op.add_column('integration_log', sa.Column('processed_rows', sa.Integer(), nullable=False, comment='Обработано файлов'))
    op.add_column('integration_log', sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Лог сообщений'))
    op.add_column('integration_log', sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ошибки'))
    op.add_column('integration_log', sa.Column('current_step', sa.String(length=255), nullable=False, comment='Текущий шаг'))
    op.add_column('integration_log', sa.Column('order_number', sa.String(length=100), nullable=False, comment='Текущий номер заказа'))
    op.alter_column('integration_log', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Профиль (если импорт по одному)',
               existing_comment='Профиль')
    op.alter_column('integration_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус: starting, processing, completed, failed',
               existing_comment='Статус',
               existing_nullable=False)
    op.alter_column('integration_log', 'total_rows',
               existing_type=sa.INTEGER(),
               comment='Всего файлов',
               existing_comment='Всего строк',
               existing_nullable=False)
    op.alter_column('integration_log', 'file_id',
               existing_type=sa.INTEGER(),
               comment='Файл с ошибками (Excel)',
               existing_comment='Файл',
               existing_nullable=True)
    op.drop_column('integration_log', 'error_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_log', sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Детали ошибок'))
    op.alter_column('integration_log', 'file_id',
               existing_type=sa.INTEGER(),
               comment='Файл',
               existing_comment='Файл с ошибками (Excel)',
               existing_nullable=True)
    op.alter_column('integration_log', 'total_rows',
               existing_type=sa.INTEGER(),
               comment='Всего строк',
               existing_comment='Всего файлов',
               existing_nullable=False)
    op.alter_column('integration_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус',
               existing_comment='Статус: starting, processing, completed, failed',
               existing_nullable=False)
    op.alter_column('integration_log', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Профиль',
               existing_comment='Профиль (если импорт по одному)')
    op.drop_column('integration_log', 'order_number')
    op.drop_column('integration_log', 'current_step')
    op.drop_column('integration_log', 'errors')
    op.drop_column('integration_log', 'messages')
    op.drop_column('integration_log', 'processed_rows')
    op.drop_column('integration_log', 'document_type')
    op.drop_column('integration_log', 'task_id')
    # ### end Alembic commands ###
