"""add notification rules

Revision ID: 4c35be5cedb5
Revises: 7e00b1686be2
Create Date: 2026-08-20 18:49:15.397335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c35be5cedb5'
down_revision: Union[str, Sequence[str], None] = '7e00b1686be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_rule',
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Тип события'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='Канал: app, email'),
    sa.Column('recipient_type', sa.String(length=30), nullable=False, comment='Тип получателя: user, role'),
    sa.Column('recipient_id', sa.Integer(), nullable=True, comment='ID пользователя (если recipient_type=user)'),
    sa.Column('role_code', sa.String(length=50), nullable=True, comment='Код роли (если recipient_type=role)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Правило активно'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['role_code'], ['accounts_role.code'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_rule')
    # ### end Alembic commands ###
