"""add orders models

Revision ID: 7db7e1206b1f
Revises: 4c35be5cedb5
Create Date: 2026-08-21 16:23:17.300304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db7e1206b1f'
down_revision: Union[str, Sequence[str], None] = '4c35be5cedb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_inbound',
    sa.Column('depositor_id', sa.Integer(), nullable=False, comment='Поклажедатель'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='Склад'),
    sa.Column('number', sa.String(length=100), nullable=False, comment='Номер заявки'),
    sa.Column('supplier_code', sa.String(length=100), nullable=False, comment='Код поставщика'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='Дата заявки'),
    sa.Column('planned_date', sa.Date(), nullable=True, comment='Планируемая дата приёмки'),
    sa.Column('notes', sa.Text(), nullable=False, comment='Примечания'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус заявки'),
    sa.Column('pordrsp_exported', sa.Boolean(), nullable=False, comment='Отклик pordrsp выгружен'),
    sa.Column('recadv_exported', sa.Boolean(), nullable=False, comment='Подтверждение recadv выгружено'),
    sa.Column('has_shortage', sa.Boolean(), nullable=False, comment='Есть недогруз'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['depositor_id'], ['parties_depositor.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_outbound',
    sa.Column('depositor_id', sa.Integer(), nullable=False, comment='Поклажедатель'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='Склад'),
    sa.Column('number', sa.String(length=100), nullable=False, comment='Номер заявки'),
    sa.Column('customer_code', sa.String(length=100), nullable=False, comment='Код клиента'),
    sa.Column('customer_name', sa.String(length=255), nullable=False, comment='Наименование клиента'),
    sa.Column('delivery_address_name', sa.String(length=255), nullable=False, comment='Адрес доставки'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='Дата заявки'),
    sa.Column('shipping_date', sa.Date(), nullable=True, comment='Планируемая дата отгрузки'),
    sa.Column('needs_delivery', sa.Boolean(), nullable=False, comment='Нужна доставка'),
    sa.Column('delivery_only', sa.Boolean(), nullable=False, comment='Только доставка (без склада)'),
    sa.Column('places_count', sa.Integer(), nullable=True, comment='Количество мест'),
    sa.Column('declared_weight', sa.Numeric(precision=12, scale=3), nullable=True, comment='Заявленный вес, кг'),
    sa.Column('delivery_contact', sa.String(length=255), nullable=False, comment='Контакт для доставки'),
    sa.Column('notes', sa.Text(), nullable=False, comment='Примечания'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус заявки'),
    sa.Column('ordrsp_exported', sa.Boolean(), nullable=False, comment='Отклик ordrsp выгружен'),
    sa.Column('desadv_exported', sa.Boolean(), nullable=False, comment='Уведомление desadv выгружено'),
    sa.Column('zone_id', sa.Integer(), nullable=True, comment='Зона доставки'),
    sa.Column('document_number', sa.String(length=100), nullable=False, comment='Номер документа'),
    sa.Column('is_printed', sa.Boolean(), nullable=False, comment='Документы распечатаны'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID для QR'),
    sa.Column('delivery_status', sa.String(length=20), nullable=True, comment='Статус доставки'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['depositor_id'], ['parties_depositor.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse_warehouse.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['parties_delivery_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('orders_inbound_line',
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Заявка'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='Товар'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Количество'),
    sa.Column('batch_number', sa.String(length=100), nullable=False, comment='Номер партии'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='Дата изготовления'),
    sa.Column('serial_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Серийные номера'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders_inbound.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['warehouse_product.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_return',
    sa.Column('outbound_order_id', sa.Integer(), nullable=False, comment='Исходный исходящий заказ'),
    sa.Column('inbound_order_id', sa.Integer(), nullable=True, comment='Созданный приходный заказ'),
    sa.Column('depositor_id', sa.Integer(), nullable=False, comment='Поклажедатель'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='Склад'),
    sa.Column('customer_code', sa.String(length=100), nullable=False, comment='Код клиента'),
    sa.Column('customer_name', sa.String(length=255), nullable=False, comment='Наименование клиента'),
    sa.Column('return_date', sa.Date(), nullable=False, comment='Дата возврата'),
    sa.Column('return_type', sa.String(length=20), nullable=False, comment='Тип возврата: full, partial'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус возврата'),
    sa.Column('notes', sa.Text(), nullable=False, comment='Примечания'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['depositor_id'], ['parties_depositor.id'], ),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['orders_inbound.id'], ),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['orders_outbound.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_outbound_line',
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Заявка'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='Товар'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Количество'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='Ячейка'),
    sa.Column('batch_number', sa.String(length=100), nullable=False, comment='Номер партии'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='Дата изготовления'),
    sa.Column('serial_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Серийные номера'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders_outbound.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['warehouse_product.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_return_line',
    sa.Column('return_order_id', sa.Integer(), nullable=False, comment='Возврат'),
    sa.Column('outbound_order_line_id', sa.Integer(), nullable=True, comment='Исходная строка'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Товар'),
    sa.Column('qty_returned', sa.Numeric(precision=10, scale=3), nullable=False, comment='Количество возвращаемого товара'),
    sa.Column('batch_number', sa.String(length=100), nullable=False, comment='Партия'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='Дата производства'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Причина возврата'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['outbound_order_line_id'], ['orders_outbound_line.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['warehouse_product.id'], ),
    sa.ForeignKeyConstraint(['return_order_id'], ['orders_return.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_return_line')
    op.drop_table('orders_outbound_line')
    op.drop_table('orders_return')
    op.drop_table('orders_inbound_line')
    op.drop_table('orders_outbound')
    op.drop_table('orders_inbound')
    # ### end Alembic commands ###
