"""outbound_order add address_comment, shipping_contact, total_quantity

Revision ID: 83eea76fb8df
Revises: 8898b14afdc5
Create Date: 2026-08-22 00:10:16.485992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83eea76fb8df'
down_revision: Union[str, Sequence[str], None] = '8898b14afdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_outbound', sa.Column('address_comment', sa.String(length=255), server_default='', nullable=False, comment='Комментарий к адресу'))
    op.add_column('orders_outbound', sa.Column('shipping_contact', sa.String(length=255), server_default='', nullable=False, comment='Контакт для доставки'))
    op.add_column('orders_outbound', sa.Column('total_quantity', sa.Integer(), server_default='0', nullable=False, comment='Общее количество штук'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_outbound', 'total_quantity')
    op.drop_column('orders_outbound', 'shipping_contact')
    op.drop_column('orders_outbound', 'address_comment')
    # ### end Alembic commands ###
