"""remove trade_point, update client

Revision ID: 84d402625be3
Revises: 7db7e1206b1f
Create Date: 2026-08-21 16:47:32.373270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d402625be3'
down_revision: Union[str, Sequence[str], None] = '7db7e1206b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_outbound', sa.Column('client_id', sa.Integer(), nullable=True, comment='Клиент'))
    op.create_foreign_key(None, 'orders_outbound', 'parties_client', ['client_id'], ['id'])
    op.add_column('parties_client', sa.Column('code', sa.String(length=50), nullable=False, comment='Код клиента'))
    op.add_column('parties_client', sa.Column('delivery_address_id', sa.Integer(), nullable=False, comment='Адрес доставки'))
    op.drop_constraint(op.f('uq_client_depositor_external'), 'parties_client', type_='unique')
    op.create_unique_constraint('uq_client_depositor_code_address', 'parties_client', ['depositor_id', 'code', 'delivery_address_id'])
    op.create_foreign_key(None, 'parties_client', 'parties_address', ['delivery_address_id'], ['id'])
    op.drop_column('parties_client', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties_client', sa.Column('external_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Внешний код'))
    op.drop_constraint(None, 'parties_client', type_='foreignkey')
    op.drop_constraint('uq_client_depositor_code_address', 'parties_client', type_='unique')
    op.create_unique_constraint(op.f('uq_client_depositor_external'), 'parties_client', ['depositor_id', 'external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('parties_client', 'delivery_address_id')
    op.drop_column('parties_client', 'code')
    op.drop_constraint(None, 'orders_outbound', type_='foreignkey')
    op.drop_column('orders_outbound', 'client_id')
    # ### end Alembic commands ###
