"""outbound_order add is_edo

Revision ID: 8898b14afdc5
Revises: eb645a31cda9
Create Date: 2026-08-21 23:55:48.753146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8898b14afdc5'
down_revision: Union[str, Sequence[str], None] = 'eb645a31cda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_outbound', sa.Column('is_edo', sa.Boolean(), server_default='false', nullable=False, comment='Признак ЭДО'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_outbound', 'is_edo')
    # ### end Alembic commands ###
