"""add delivery

Revision ID: 93624719f4ef
Revises: 1f08ff9fb1ee
Create Date: 2026-08-19 02:19:09.335144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93624719f4ef'
down_revision: Union[str, Sequence[str], None] = '1f08ff9fb1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_driver',
    sa.Column('name', sa.String(length=255), nullable=False, comment='ФИО'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Телефон'),
    sa.Column('carrier_id', sa.Integer(), nullable=True, comment='Перевозчик'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['carrier_id'], ['parties_carrier.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_vehicle',
    sa.Column('number', sa.String(length=20), nullable=False, comment='Гос. номер'),
    sa.Column('brand', sa.String(length=100), nullable=False, comment='Марка'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='Модель'),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=True, comment='Грузоподъёмность'),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=True, comment='Объём'),
    sa.Column('carrier_id', sa.Integer(), nullable=True, comment='Перевозчик'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['carrier_id'], ['parties_carrier.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_route',
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер'),
    sa.Column('driver_id', sa.Integer(), nullable=False, comment='Водитель'),
    sa.Column('vehicle_id', sa.Integer(), nullable=False, comment='Автомобиль'),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['delivery_driver.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['delivery_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_order',
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер'),
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='Договор'),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='Документ склада'),
    sa.Column('trade_point_id', sa.Integer(), nullable=False, comment='Торговая точка'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Родительский заказ'),
    sa.Column('contact_person', sa.String(length=255), nullable=False, comment='Контактное лицо'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Телефон'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='Дата доставки'),
    sa.Column('time_from', sa.Time(), nullable=True, comment='Время с'),
    sa.Column('time_to', sa.Time(), nullable=True, comment='Время до'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='Статус'),
    sa.Column('is_edo', sa.Boolean(), nullable=False, comment='Признак ЭДО'),
    sa.Column('comment', sa.Text(), nullable=False, comment='Комментарий'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['contract_id'], ['parties_contract.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents_document.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['delivery_order.id'], ),
    sa.ForeignKeyConstraint(['trade_point_id'], ['parties_trade_point.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_deviation',
    sa.Column('delivery_order_id', sa.Integer(), nullable=False, comment='Заказ на доставку'),
    sa.Column('deviation_type', sa.String(length=20), nullable=False, comment='Тип отклонения'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество мест'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_order.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_route_line',
    sa.Column('route_id', sa.Integer(), nullable=False, comment='Маршрут'),
    sa.Column('delivery_order_id', sa.Integer(), nullable=False, comment='Заказ на доставку'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Порядок'),
    sa.Column('planned_time', sa.Time(), nullable=True, comment='Плановое время'),
    sa.Column('actual_time', sa.Time(), nullable=True, comment='Фактическое время'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_order.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['delivery_route.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_route_line')
    op.drop_table('delivery_deviation')
    op.drop_table('delivery_order')
    op.drop_table('delivery_route')
    op.drop_table('delivery_vehicle')
    op.drop_table('delivery_driver')
    # ### end Alembic commands ###
