"""add notifications

Revision ID: b08740017c7f
Revises: ca6ede83997e
Create Date: 2026-08-19 03:50:22.396843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08740017c7f'
down_revision: Union[str, Sequence[str], None] = 'ca6ede83997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_notification',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Получатель'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Заголовок'),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст'),
    sa.Column('notification_type', sa.String(length=20), nullable=False, comment='Тип уведомления'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус'),
    sa.Column('link', sa.String(length=500), nullable=False, comment='Ссылка'),
    sa.Column('sent_at', sa.String(length=50), nullable=True, comment='Когда отправлено'),
    sa.Column('read_at', sa.String(length=50), nullable=True, comment='Когда прочитано'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Обновлена'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='Создал (user ID)'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='Изменил (user ID)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Удалена (soft)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Удалена (когда)'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='Удалил (user ID)'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_notification')
    # ### end Alembic commands ###
