"""add unique order number

Revision ID: c175f41bdbc5
Revises: 398d85319f7a
Create Date: 2026-08-21 17:01:42.988368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c175f41bdbc5'
down_revision: Union[str, Sequence[str], None] = '398d85319f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inbound_depositor_number', 'orders_inbound', ['depositor_id', 'number'])
    op.create_unique_constraint('uq_outbound_depositor_number', 'orders_outbound', ['depositor_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_outbound_depositor_number', 'orders_outbound', type_='unique')
    op.drop_constraint('uq_inbound_depositor_number', 'orders_inbound', type_='unique')
    # ### end Alembic commands ###
