"""add address components

Revision ID: ca6ede83997e
Revises: 7a1d96aa6c32
Create Date: 2026-08-19 03:36:33.165299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6ede83997e'
down_revision: Union[str, Sequence[str], None] = '7a1d96aa6c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties_address', sa.Column('region', sa.String(length=255), nullable=False, server_default='', comment='Регион'))
    op.add_column('parties_address', sa.Column('city', sa.String(length=255), nullable=False, server_default='', comment='Город'))
    op.add_column('parties_address', sa.Column('street', sa.String(length=255), nullable=False, server_default='', comment='Улица'))
    op.add_column('parties_address', sa.Column('house', sa.String(length=64), nullable=False, server_default='', comment='Дом'))
    op.add_column('parties_address', sa.Column('building', sa.String(length=32), nullable=False, server_default='', comment='Корпус'))
    op.add_column('parties_address', sa.Column('structure', sa.String(length=32), nullable=False, server_default='', comment='Строение'))
    op.add_column('parties_address', sa.Column('flat', sa.String(length=32), nullable=False, server_default='', comment='Квартира'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties_address', 'flat')
    op.drop_column('parties_address', 'structure')
    op.drop_column('parties_address', 'building')
    op.drop_column('parties_address', 'house')
    op.drop_column('parties_address', 'street')
    op.drop_column('parties_address', 'city')
    op.drop_column('parties_address', 'region')
    # ### end Alembic commands ###
