"""delivery_order add outbound_order_id, contract nullable

Revision ID: eb645a31cda9
Revises: f502155ea958
Create Date: 2026-08-21 21:57:53.875080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb645a31cda9'
down_revision: Union[str, Sequence[str], None] = 'f502155ea958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_order', sa.Column('outbound_order_id', sa.Integer(), nullable=True, comment='Исходящий заказ'))
    op.alter_column('delivery_order', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Договор перевозки',
               existing_comment='Договор')
    op.create_foreign_key(None, 'delivery_order', 'orders_outbound', ['outbound_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_order', type_='foreignkey')
    op.alter_column('delivery_order', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Договор',
               existing_comment='Договор перевозки')
    op.drop_column('delivery_order', 'outbound_order_id')
    # ### end Alembic commands ###
