"""add supplier_id to inbound

Revision ID: f502155ea958
Revises: 3da6fcf45d11
Create Date: 2026-08-21 20:57:53.015879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f502155ea958'
down_revision: Union[str, Sequence[str], None] = '3da6fcf45d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_inbound', sa.Column('supplier_id', sa.Integer(), nullable=True, comment='Поставщик'))
    op.create_foreign_key(None, 'orders_inbound', 'parties_client', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_inbound', type_='foreignkey')
    op.drop_column('orders_inbound', 'supplier_id')
    # ### end Alembic commands ###
